# Generated by Django 4.2.2 on 2023-06-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('PR', 'Priority'), ('AT', 'Attention'), ('GR', 'Green')], default='GR', max_length=2)),
            ],
        ),
    ]
