# Generated by Django 4.2.2 on 2023-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
